services:

  checkmk:
    image: checkmk/check-mk-raw:latest
    container_name: checkmk    
    restart: unless-stopped
    ulimits:
      nofile: 1024
    ports:
      - "8200:5000"
      - "8800:8000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./monitoring:/omd/sites

      
