services:

  checkmk:
    image: checkmk/check-mk-raw:latest
    container_name: checkmk    
    restart: unless-stopped
    stdin_open: true
    tty: true
    tmpfs: /opt/omd/sites/cmk/tmp:uid=1000,gid=1000    
    ulimits:
      nofile: 1024
    ports:
      - "8200:5000"
      - "8800:8000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./checkmk:/omd/sites
    
